server:
  port: 8090

# DataSource settings: set here configurations for the database connection
#spring.jpa.hibernate.ddl-auto
spring:
  datasource:
    platform: "postgres"
    url: "jdbc:postgresql://localhost:5432/qijeu_db_dev"
    username: "qijeu_user"
    password: "qijeu_pwd"
  jpa:
    hibernate:
      ddl-auto: "validate"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        current_session_context_class: "thread"
        format_sql: true  
      jdbc:
        lob:
          non_contextual_creation: true
      javax:
        persistence:
          schema-generation:
            scripts:
              action: "create"
              create-target: "create.sql"
              create-source: "metadata"
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      max-file-size: "200MB"
      max-request-size: "200MB"
  liquibase:
    enabled: true
    change-log: classpath:liquibase-outputChangeLog.yaml
#security:
#  oauth2:
#    client:
#      registration:
#        github:
#          clientId: github-client-id
#          clientSecret: github-client-secret

#######################################
#  Variables QIJEU
#######################################
#Activation du mode test et parametrage
qijeu:
  cors: "*"
  mode:
    test: true
  nb:
    clients: 10
    equipes: 10
    competitions: 10
    jeux: 10
